### ISSUE TITLE
FileNotFoundException when no processes folder

### ISSUE THREAD

**Issue by ptahchiev** [Activiti/activiti-cloud-runtime-bundle-service#56]
I use 

````
        <dependency>
            <groupId>org.activiti.cloud</groupId>
            <artifactId>activiti-cloud-starter-configure</artifactId>
            <version>7-201802-EA</version>
        </dependency>
````

and when I start my spring-boot app I get this exception:
````
Caused by: java.io.FileNotFoundException: class path resource [processes/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:495)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:296)
	at org.springframework.context.support.AbstractApplicationContext.getResources(AbstractApplicationContext.java:1309)
	at org.springframework.context.support.GenericApplicationContext.getResources(GenericApplicationContext.java:233)
	at org.activiti.spring.boot.AbstractProcessEngineConfiguration.discoverProcessDefinitionResources(AbstractProcessEngineConfiguration.java:77)
	at org.activiti.spring.boot.AbstractProcessEngineAutoConfiguration.baseSpringProcessEngineConfiguration(AbstractProcessEngineAutoConfiguration.java:74)
	at org.activiti.spring.boot.ProcessEngineAutoConfiguration.springProcessEngineConfiguration(ProcessEngineAutoConfiguration.java:45)
	at org.activiti.spring.boot.ProcessEngineAutoConfiguration$$EnhancerBySpringCGLIB$$cc380ed7.CGLIB$springProcessEngineConfiguration$0(<generated>)
	at org.activiti.spring.boot.ProcessEngineAutoConfiguration$$EnhancerBySpringCGLIB$$cc380ed7$$FastClassBySpringCGLIB$$7638b10.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.activiti.spring.boot.ProcessEngineAutoConfiguration$$EnhancerBySpringCGLIB$$cc380ed7.springProcessEngineConfiguration(<generated>)

````

**Comment by Salaboy** [comment]
@ptahchiev hi there. you need to store your process bpmn files inside that processes/ folder. 
That can be configured, but that is the default location. 
We are working to support multiple approaches for defining your business models.
